FROM node:alpine
LABEL maintainer="lanyuhang@baidu.com"

WORKDIR /tester

COPY ./tester/package.json .

RUN npm --silent --progress=false install > /dev/null \
  && rm -rf /tmp/* ~/.npm

COPY ./tester/ .

CMD sleep 100s \
  && ./node_modules/.bin/mocha test.js -t 10000
